language: python
python:
- '2.7'
before_script:
- yes | python setup.py install
- git clone https://github.com/uc-cdis/dictionaryutils; cd dictionaryutils
script:
- "./run_tests.sh"
deploy:
  provider: s3
  access_key_id: AKIAZRNPHKJIPRRTEJUI
  secret_access_key:
    secure: i+b2ygmrMbp2b0pM0r0IZi0R4zVuIWxEs8nIaNsHMq4bGuP8yfaURaSV9MfIZ/KikeDxUyWoMuZcqKrjDE+yCU2ocHNqRrPmG0Z1UfdAPpSpF3IbcxJWYO55UTs8LvWwTnRDnfgvLB5X6dM5wH/qOA7eziDYJrDgrGOzj+qeQN52BzvaeFPE+jxgizCyQDCrJ7XkdANkIhGMfUhkp85/ff/cZRUPUTnIZjzJA1eEIX6Id8kT2dr9q6VNCcRAgh4tKXUvG0Cv4HMHHAlurqhDoSnDmia1OGcCqxto+xRs8v6/anJuMOmuUzK1bNCEwLgIMHLdXR9wDsqlLNDd5ZeoN3LVKKGVFo/lIx18kwlGpJWFEtCGoZOWYOAVW4quqwljUzyUT+UoRlGYGo0+onVS37hCEacmd3TlPasY0LmpwB9zyxwY2sYfLpsYwJ2jTvS6rhs49NUsbGZdlG6dXNnS+V+6lM4VYQ7nQgYTZ8KO+x2CWPKzGkd8oQUwa0mfPE1/XDD7YobttO0S4fEsxYiNK4H6eJhY5OX06+GJLJUumwWTfLYAJxV1s8qKtW5QU8XahCJb4srTSWbJjoWDJMir9mAzNosQHssgqQwzIB8bYCXH8+1WpKjmjdfU1LYu7d9X7cRVd/Z+T/bJdElnT5IHavsxygSwkg4lklWLqK6Rgu8=
  bucket: dictionary-artifacts
  local-dir: artifacts
  upload-dir: Flu_datadictionary/$TRAVIS_BRANCH
  skip_cleanup: true
  on:
    repo: uc-cdis/Flu_datadictionary
    all_branches: true
