language: python
python:
- '2.7'
before_script:
- yes | python setup.py install
- git clone https://github.com/uc-cdis/dictionaryutils; cd dictionaryutils
script:
- "./run_tests.sh"
deploy:
  provider: s3
  access_key_id: AKIAZRNPHKJIPRRTEJUI
  secret_access_key:
    secure: Gnqx5eyTh+NDNBrPZi68k25mkh6pB1nsyb25FFxAkOMv7NosAX4IOeZiqObTrR+qSe5Zt7QxI/4/wlGCnoAEVZDP3pnqmIIc9div15bKjkPj2Ff1QT5/sD8pBQb0Do3HUxUqvUj/M0Zn3QN1tuvMjhk6RvRIN9lBJP0eTMBJqjS/jI3a3S/gaxTie5KkC8Sf/FSH4PqJu65uBPO3MvSA6idvlSJm6rouN2vfhBtNLn0z2CNgH19FM6pV8xdqQ/8++aiLCzmH0qgDIMt2HVNuRgsulFagUaCY6LMPQEi8XYMUHfNcJeT+SuBaQynDdAGqJVjj2xwQMkBBcV9t6yOEBZToscCdIgHk0uDTBclSScFzHF0kW0JHU571q6uCZnRoIpUPxGVHglFEoHyMYjvfxCSpvbQRCYDRic8/LEMOyYY+BKumdmWfmcsHna+cu0lAeWHQvtM25jEYACoOXrDo4lTb6xyQKxVPmzTCP4mhzLu8Ez3u+TgUA0KKcujPHeXHZOkD77cb0CgmW79B1QX3+KZA6X+s3/QgcTbyuz/0eXRQKwDeKLjeV9C4Fv95Mn0PXTqF7Dt5NlqKW9xtwbMQJK8MHJXQPkclJww6o9MNYjw9h1hC5VeHIEuWwFXOIpSGUp04Hqu65VNd+Vz9bF6mds/fXfotCa23JqtXBT8Q5J8=
  bucket: dictionary-artifacts
  local-dir: artifacts
  upload-dir: Flu_datadictionary/$TRAVIS_BRANCH
  skip_cleanup: true
  on:
    repo: uc-cdis/Flu_datadictionary
    all_branches: true
