language: python
python:
- '2.7'
before_script:
- yes | python setup.py install
- git clone https://github.com/uc-cdis/dictionaryutils; cd dictionaryutils
script:
- "./run_tests.sh"
deploy:
  provider: s3
  access_key_id: AKIAZRNPHKJIPRRTEJUI
  secret_access_key:
    secure: fkzddDoXvezJklLC+AVwxBtqz+3sN8Y7EsO7cPcaw6lRtqPfXzgmpl3J+4A4d4j1nONoo1otIEit8dQz1P5ILRx9NlmgbhsUNwNHnblBEiCDXYxKX4NHgK2Wac4PRPVgXWBiqACrS+8q+bR1UPdWGLlwwIpLWa7yGl9i7JDuvo1VT9iwwViw0jPRzIUQ+2zCKYCIJCEGg6Bg+tM1Rf/ZH5jh1TDjeo49vkV6PDDPvUKs8gFoWJDaF6cDGzTiS8aqkGkQSVNouEW4BNj7j01Nxq9qjnFiuzFjTuMJVtSUMfXNH8GLG6OLhLNTODePEt9wSXlcNsBiCKUtWWtOaBJcqcR3XnnaqLGiL3rBOBQQosGyJ6H0XQADroVhWaXs7Vfs27QNSPsSbKKynKB48b8O2ruK8DRJxxbLtjpim2V3uvh8dwB6mCRw7675tqvaolaDCs+JJjFZsi0qltIzYQY/N5QZJWQ4n7W6y7IuqzJPlC59S+n63LdkMIsNMa5W2CTY6F0bMhGRfBFxFZKaRd8650KDvT6DrUiS7CxQv99/RtOXLpw+BV6KMZiZbzRJx+hCY0LBtAqQHB/FEjJJZsgVZVeiRFdWHLVUPWAFLhGDdufpHHRfcsSbDRSp8KH3Dm0gHB96fqEbBobtjHutLH1ZxHf658cLqYGsPA5zrMrovok=
  bucket: dictionary-artifacts
  local-dir: artifacts
  upload-dir: Flu_datadictionary/$TRAVIS_BRANCH
  skip_cleanup: true
  on:
    repo: uc-cdis/Flu_datadictionary
    all_branches: true
