language: python
python:
- '2.7'
before_script:
- yes | python setup.py install
- git clone https://github.com/uc-cdis/dictionaryutils; cd dictionaryutils
script:
- "./run_tests.sh"
deploy:
  provider: s3
  access_key_id: AKIAJ2CEZVTSFRBCKRJQ
  secret_access_key:
    secure: i1Zdtr6X0QHc8dARW27ivcCqr9+smJj5AEtl8Gn/leP0eKQ6uZ3nQaf3aliHpkze45ZsnbPpievRa261UPK0gXBa8pD2O1L7RDJdLjcRA2RwF8y/Cql05AKBxsXG8afY/zzrqJ7E3T5U0HezrsmYwNrA1+7Lp9kgt4GH90iAFsHa5FuwdQLt1nYTPbvIqyXo5nDnAo8WF1/QS9iMHvtKF+T7c92xdUxBMCyw7GcG08SkI5G4F7ix1zVFOxZbRY3fSzDM+jlsfPltPl22yGLA0ukq+vxRnOC/Bu6O7YqpCKjr6UUs3YX4nqnmCytwhLVTuzog3o069BJhKuKeoYN8gIA2MRMB0yQEz20m20atf7a0njNqXUOamBu2Z7TulhNnA0XHKtbaGXo9M4ww9D0swtqqJL6szjv3WREhe9hS+3muWtGN+E/leK7apRUUXNkMV8CppJuXPIiISaKKL1Djlu98+LleCgKt3LcSeuGv3NwAgjOD1N8gAZ7sYK/ZTX82zAi0K8V5Sb3Y1cN64NVNjzbfcDKbHXB4c7Bnc7LQ9Tjsta2YvFI7Cul+SpXd/Czizree1U7qdakc5P9zFV0aliySLcP/MGeBtSh1KTz9NkXOqYm5E8Udw3YKrKtJFykS1p8N4l5nIBOvODVJpS2efBksOrR1tqefFaJnjs99Gec=
  bucket: dictionary-artifacts
  local-dir: artifacts
  upload-dir: ndhdictionary/$TRAVIS_BRANCH
  skip_cleanup: true
  on:
    repo: uc-cdis/ndhdictionary
    all_branches: true
