language: python
python:
- '2.7'
before_script:
- yes | python setup.py install
- git clone https://github.com/uc-cdis/dictionaryutils; cd dictionaryutils
script:
- "./run_tests.sh"
deploy:
  provider: s3
  access_key_id: AKIAJ2CEZVTSFRBCKRJQ
  secret_access_key:
    secure: DG4VSTJWJ5Q8iazKtOkeinqKVIiTDlGEII18QHcoeNlW05yu2Kpgg1AiMv61KHi1p7L20d9HCLDHX2oXg+KjWDmt4GsEDM1IgOcVF2TJo9gNdzxFoH6UnbOlGyWLKHZ/7y2qfG/tdJZRAbvYT/t50KSZai2qTmPOWsgSB0rOCWKTRmGJE6cgaVwlMGPtdNZxpCpurz5J0cDdViHLinS9QootBuxCee66mLF47MclZuYIvqVzOG7SA5DD2qKs1shmmXhp+2ybpl0AqNzPv9smLHpvrbz3F3QpHOVqNud7WHWGtaMbs3rndsMzFjof1KHSGXYoJsu/YA3xGbrz/GRhE5HG8gDVrxKM744pC0MSO7JQyvzimRJDALIRzHLnP8g4U3/gnPfoGUNmNjci7OVP/r3tus7HyEJa57nlWsldlzU+tmL9mghH7kth54gdgcgBJCaTbP58D3hzVdPDFrCcF0hnJepQHpBYRtqL/mAwIdQbqJFYdIZphUoba+9ZQbV1/LSIeeBZmOmelvRcnwMedpnM9KRs7C4W8rTJlLspnMhHwS8LJC0TpOUnKfixt/QJjAZtl6e/LvDHaajv9PQl8ddFIFsUBUhcRTSZtf/Q1JRODNNTERbYIj9yYfemPf142DzPINnP7TEfa5bXt7/E7mqbvoBa3thfaIzeXDi6CTY=
  bucket: dictionary-artifacts
  local-dir: artifacts
  upload-dir: Flu_datadictionary/$TRAVIS_BRANCH
  skip_cleanup: true
  on:
    repo: uc-cdis/Flu_datadictionary
    all_branches: true
